# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8081
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100

# Spring配置
spring:
  application:
    name: demo
  profiles:
    active: []
  main:
    banner-mode: off
  messages:
    encoding: UTF-8
    basename: i18n/messages
  output:
    ansi:
      enabled: always
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  jackson:
    default-property-inclusion: always
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      write-bigdecimal-as-plain: true
      write-dates-as-timestamps: false
    deserialization:
      adjust-dates-to-context-time-zone: false
  mybatis-page:
    max-page-size: 100
    default-page-size: 10
  redis:
    host: 45.125.46.48
    port: 47294
    database: 0
    password:
    timeout: 10s
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: -1ms
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  datasource-ruoyi:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://45.125.46.48:29772/ry-vue
    username: root
    password: bin
    connection-timeout: 30000
    connection-test-query: SELECT 1
    max-lifetime: 30000
    idle-timeout: 30000
    maximum-pool-size: 5
    minimum-idle: 0
  task:
    scheduling:
      pool:
        size:

# 日志配置
logging:
  file:
    name: ./logs/${spring.application.name:log}.log
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} %highlight(%-5level) [%blue(%thread)] - %cyan(%logger{50}) : %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] - %logger{50} - %msg%n'
  logback:
    rollingpolicy:
      max-history: 30
      clean-history-on-start: true
      max-file-size: 10MB
  level:
    root: info
    org.springframework: warn

mybatis-plus:
  global-config:
    banner: false
    db-config:
      id-type: none
  configuration:
    cache-enabled: true
    use-generated-keys: true
    default-executor-type: simple
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true
  group-configs:
    - group: 'default'
      paths-to-match: '/**'

# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 30
# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*
# 项目相关配置
ruoyi:
  # 名称
  name: RuoYi
  # 版本
  version: 3.8.5
  # 版权年份
  copyrightYear: 2023
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/ruoyi/uploadPath，Linux配置 /home/ruoyi/uploadPath）
  profile: D:/ruoyi/uploadPath
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数组计算 char 字符验证
  captchaType: math
# 用户配置
user:
  password:
    # 密码最大错误次数
    maxRetryCount: 5
    # 密码锁定时间（默认10分钟）
    lockTime: 10
